# Generated by Django 5.1.7 on 2025-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(null=True),
        ),
    ]
